print("""

██╗      ██████╗ ███╗   ███╗██████╗ ██████╗ 
██║     ██╔═══██╗████╗ ████║╚════██╗╚════██╗
██║     ██║   ██║██╔████╔██║ █████╔╝ █████╔╝
██║     ██║▄▄ ██║██║╚██╔╝██║ ╚═══██╗ ╚═══██╗
███████╗╚██████╔╝██║ ╚═╝ ██║██████╔╝██████╔╝
╚══════╝ ╚══▀▀═╝ ╚═╝     ╚═╝╚═════╝ ╚═════╝ 



BU PROGRAM LQM33 TARAFINDAN HAZIRLANMIŞTIR İLETİŞİM
instagram: lqm33.py
Program GPL Lisansı tarafından korunmaktadır :)
"""  )



ad = input("Kurbanın Adı Gir ...:")
soyad = input("Kurbanın Soyadı Gir ...:")
dogum = input("Kurbanın Doğum Tarihini Gir ...:")
print("UFAK BİLGİ |GS = 1905 FB= 1907 BJK = 1903|")
takım = input("Kurbanı Tuttuğu Takımın Kuruluş yılını Gir ...:")
takımkısa = input("Kurbanın  Tuttuğu Takımın Kısaltmasını Gir ...:")
id = input("Kurbanın İnstagram Kullanıcı Adını Gir...:")
s0 = soyad [0]
s1 = soyad [1]
print(ad + soyad)
print(ad + soyad + dogum)
print(ad + soyad + dogum + takım)
print(ad + soyad + dogum + takım +takımkısa)
print(ad + dogum + soyad)
print(ad + dogum + soyad + takım)
print(ad + dogum + soyad + takım + takımkısa)
print(ad + takım + soyad)
print(ad + takım + soyad + takımkısa)
print(ad + takımkısa + soyad)
print(ad + takımkısa + soyad + dogum)
print(ad + takımkısa +soyad + dogum + takım )
print(ad + soyad + ad )
print(ad + takım + takımkısa)
print(ad + takımkısa + soyad + ad )
print(soyad + ad)
print(soyad + ad + dogum)
print(soyad + ad + dogum + takım)
print(soyad + ad + dogum + takım +takımkısa)
print(soyad + ad + soyad)
print(soyad + ad + soyad + takım)
print(soyad +  ad+ soyad + takım + takımkısa)
print(soyad + takım + ad)
print(soyad + takım + ad+ takımkısa)
print(soyad + takımkısa + ad)
print(soyad + takımkısa + ad + dogum)
print(soyad + takımkısa + ad + dogum + takım )
print(soyad + soyad + ad )
print(soyad + takım + takımkısa)
print(soyad + takımkısa + soyad + ad )
print(ad  + "1234" + soyad )
print (ad + "123" + soyad)
print (ad + "123" + soyad + takımkısa)
print(ad + "1234" + soyad + takımkısa)
print(ad + "1234" + soyad + takım)
print (ad + "123" + soyad + takım)
print(ad + soyad + s0 + s1)
print(ad + soyad + s0 + s1+takım)
print(ad + soyad + s0 + s1+takım+takımkısa)
print(ad + soyad +"123"+ s0 + s1)
print(ad + soyad +"1234"+ s0 + s1)
print(ad + soyad +"123"+ s0 + s1+takım)
print(ad + soyad +"123"+ s0 + s1+ takım +takımkısa)
print(ad + soyad +"1234"+ s0 + s1+takım)
print(ad + soyad +"1234"+ s0 + s1+takım+takımkısa)
print(takım +ad + soyad + s0 + s1)
print(takımkısa +ad + soyad + s0 + s1)
print(takım + soyad +ad + s0 + s1)
print(takım + ad)
print(takım + ad +soyad)
print(takım + ad + "123")
print(takım + ad + "1234")
print(takım + ad +"123"+ s0 + s1)
print(takım + ad+"1234"+ s0+ s1)
print(takımkısa +ad + soyad + s0 + s1)
print(takım+"1234" +ad + soyad + s0 + s1)
print(takımkısa + soyad +ad + s0 + s1)
print(takımkısa + ad)
print(takımkısa + ad +soyad)
print(takımkısa + ad + "123")
print(takımkısa + ad + "1234")
print(takımkısa + ad +"123"+ s0 + s1)
print(takımkısa + ad+"1234"+ s0+ s1)
print(takım + ad + takımkısa)
print(takımkısa +ad+takımkısa)
print(takım + takımkısa + ad)
print(ad  + "1234" + s0+s1 )
print (ad + "123" + s0+s1)
print (ad + "123" + soyad + takımkısa+takım)
print(ad + "1234" + soyad + takım)
print(ad + "1234"+soyad + takımkısa+takım)
print(ad + "1234" + soyad + takım+s0+s1)
print (ad + "123" + soyad + takım+s0+s1)
print(takımkısa+takım+ad)
print(ad+soyad+ takım+"123")
print(ad+soyad +takım + "1234")
print(ad+soyad+takım + takımkısa + "1234")
print(id + soyad)
print(id + soyad + dogum)
print(id + soyad + dogum + takım)
print(id + soyad + dogum + takım +takımkısa)
print(id + dogum + soyad)
print(id + dogum + soyad + takım)
print(id + dogum + soyad + takım + takımkısa)
print(id + takım + soyad)
print(id + takım + soyad + takımkısa)
print(id + takımkısa + soyad)
print(id + takımkısa + soyad + dogum)
print(id + takımkısa +soyad + dogum + takım )
print(id + soyad + ad )
print(id + takım + takımkısa)
print(id + takımkısa + soyad + ad )
print(soyad + id)
print(soyad + id + dogum)
print(soyad + id + dogum + takım)
print(soyad + id + dogum + takım +takımkısa)
print(soyad + id + soyad)
print(soyad + id + soyad + takım)
print(soyad +  id+ soyad + takım + takımkısa)
print(soyad + takım + id)
print(soyad + takım + id+ takımkısa)
print(soyad + takımkısa + id)
print(soyad + takımkısa + id + dogum)
print(soyad + takımkısa + id + dogum + takım )
print(soyad + soyad + id )
print(soyad + takım + takımkısa)
print(soyad + takımkısa + soyad + id )
print(id  + "1234" + soyad )
print (id + "123" + soyad)
print (id + "123" + soyad + takımkısa)
print(id + "1234" + soyad + takımkısa)
print(id + "1234" + soyad + takım)
print (id + "123" + soyad + takım)
print(id + soyad + s0 + s1)
print(id + soyad + s0 + s1+takım)
print(id + soyad + s0 + s1+takım+takımkısa)
print(id + soyad +"123"+ s0 + s1)
print(id + soyad +"1234"+ s0 + s1)
print(id + soyad +"123"+ s0 + s1+takım)
print(id + soyad +"123"+ s0 + s1+ takım +takımkısa)
print(id + soyad +"1234"+ s0 + s1+takım)
print(id + soyad +"1234"+ s0 + s1+takım+takımkısa)
print(takım +id + soyad + s0 + s1)
print(takımkısa +id + soyad + s0 + s1)
print(takım + soyad +id + s0 + s1)
print(takım + id)
print(takım + id +soyad)
print(takım + id + "123")
print(takım + id + "1234")
print(takım + id +"123"+ s0 + s1)
print(takım + id+"1234"+ s0+ s1)
print(takımkısa +id + soyad + s0 + s1)
print(takım+"1234" +id + soyad + s0 + s1)
print(takımkısa + soyad +id + s0 + s1)
print(takımkısa + id)
print(takımkısa + id +soyad)
print(takımkısa + id + "123")
print(takımkısa + id + "1234")
print(takımkısa + id +"123"+ s0 + s1)
print(takımkısa + id+"1234"+ s0+ s1)
print(takım + id + takımkısa)
print(takımkısa +id+takımkısa)
print(takım + takımkısa + id)
print(id  + "1234" + s0+s1 )
print (id + "123" + s0+s1)
print (id + "123" + soyad + takımkısa+takım)
print(id + "1234" + soyad + takım)
print(id + "1234"+soyad + takımkısa+takım)
print(id + "1234" + soyad + takım+s0+s1)
print (id + "123" + soyad + takım+s0+s1)
print(takımkısa+takım+id)
print(id+soyad+ takım+"123")
print(id+soyad +takım + "1234")
print(id+soyad+takım + takımkısa + "1234")
print(ad+takım+"123321")
print(ad+takımkısa+takımkısa)
print(takımkısa+takım+takımkısa+ad)
print(ad+"123"+id)
print(ad+"1234"+id)
print(id+s0+s1)
print(id+s0+s1+ad)
print(id+s0+s1+ad+soyad)
print(id+s0+s1+ad+takım)
print(id+s0+s1+ad+takımkısa)
print(id+s0+s1+ad+"1234")
print(id)
print(id+s0+s1+soyad)
print(id+s1+s0+ad)
print(id+"123"+s0+s1+"123")
print(takım+id+takım)
print(ad+"123456"+s0+s1)
print(ad  + "1234564" + soyad )
print (ad + "123456" + soyad)
print (ad + "123456" + soyad + takımkısa)
print(ad + "1234564" + soyad + takımkısa)
print(ad + "1234564" + soyad + takım)
print (ad + "123456" + soyad + takım)
print(ad + soyad +"123456"+ s0 + s1)
print(ad + soyad +"1234564"+ s0 + s1)
print(ad + soyad +"123456"+ s0 + s1+takım)
print(ad + soyad +"123456"+ s0 + s1+ takım +takımkısa)
print(ad + soyad +"1234564"+ s0 + s1+takım)
print(ad + soyad +"1234564"+ s0 + s1+takım+takımkısa)
print(takım +ad + soyad + s0 + s1)
print(takım + ad + "123456")
print(takım + ad + "1234564")
print(takım + ad +"123456"+ s0 + s1)
print(takım + ad+"1234564"+ s0+ s1)
print(takım+"1234564" +ad + soyad + s0 + s1)
print(takımkısa + ad + "123456")
print(takımkısa + ad + "1234564")
print(takımkısa + ad +"123456"+ s0 + s1)
print(takımkısa + ad+"1234564"+ s0+ s1)
print(ad  + "1234564" + s0+s1 )
print (ad + "123456" + s0+s1)
print (ad + "123456" + soyad + takımkısa+takım)
print(ad + "1234564" + soyad + takım)
print(ad + "1234564"+soyad + takımkısa+takım)
print(ad + "1234564" + soyad + takım+s0+s1)
print (ad + "123456" + soyad + takım+s0+s1)
print(ad+soyad+ takım+"123456")
print(ad+soyad +takım + "1234564")
print(ad+soyad+takım + takımkısa + "1234564")
print(id  + "1234564" + soyad )
print (id + "123456" + soyad)
print (id + "123456" + soyad + takımkısa)
print(id + "1234564" + soyad + takımkısa)
print(id + "1234564" + soyad + takım)
print (id + "123456" + soyad + takım)
print(id + soyad +"123456"+ s0 + s1)
print(id + soyad +"1234564"+ s0 + s1)
print(id + soyad +"123456"+ s0 + s1+takım)
print(id + soyad +"123456"+ s0 + s1+ takım +takımkısa)
print(id + soyad +"1234564"+ s0 + s1+takım)
print(id + soyad +"1234564"+ s0 + s1+takım+takımkısa)
print(takım + id + "123456")
print(takım + id + "1234564")
print(takım + id +"123456"+ s0 + s1)
print(takım + id+"1234564"+ s0+ s1)
print(takım+"1234564" +id + soyad + s0 + s1)
print(takımkısa + id + "123456")
print(takımkısa + id + "1234564")
print(takımkısa + id +"123456"+ s0 + s1)
print(takımkısa + id+"1234564"+ s0+ s1)
print(id  + "1234564" + s0+s1 )
print (id + "123456" + s0+s1)
print (id + "123456" + soyad + takımkısa+takım)
print(id + "1234564" + soyad + takım)
print(id + "1234564"+soyad + takımkısa+takım)
print(id + "1234564" + soyad + takım+s0+s1)
print (id + "123456" + soyad + takım+s0+s1)
print(id+soyad+ takım+"123456")
print(id+soyad +takım + "1234564")
print(id+soyad+takım + takımkısa + "1234564")
print(ad+takım+"123456321")
print(ad+"123456"+id)
print(ad+"1234564"+id)
print(id+s0+s1+ad+"1234564")
print(id+"123456"+s0+s1+"123456")
print(ad+"1234564"+id+"qwer")
print(id+s0+s1+ad+"1234564"+"000")
print(id+"123456"+s0+s1+"123456"+"qwer")
print("""




██╗      ██████╗ ███╗   ███╗██████╗ ██████╗ 
██║     ██╔═══██╗████╗ ████║╚════██╗╚════██╗
██║     ██║   ██║██╔████╔██║ █████╔╝ █████╔╝
██║     ██║▄▄ ██║██║╚██╔╝██║ ╚═══██╗ ╚═══██╗
███████╗╚██████╔╝██║ ╚═╝ ██║██████╔╝██████╔╝
╚══════╝ ╚══▀▀═╝ ╚═╝     ╚═╝╚═════╝ ╚═════╝ 
                                """)
input("Bitti bak kopladın mı ?")
input("Bak emin misin ? ?")
















